### ISSUE TITLE
Our extension breaks twitter since inclusion of chakra-ui

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/aqua-verifypage-chrome-extension#52]
![image](https://user-images.githubusercontent.com/45313235/148935400-fe586300-0ef8-4ec4-9898-190229211b02.png)

**Comment by rht** [comment]
Fixed in https://github.com/inblockio/aqua-verifypage-chrome-extension/commit/d89781e08bee2d5feace9119bfd5fcd6ccc8b4e8.
